### ISSUE TITLE
Incorrect troubleshooting links

### ISSUE THREAD

**Issue by OatmealDome** [Plailect/Guide#18]
Steps 18 and 24 under Part 4, Section II link to the wrong troubleshooting section. (They link to "Black screen on SysNAND boot after downgrading" though it appears they should link to "OTPHelper fails to verify my NAND" instead)

**Comment by Plailect** [comment]
fixed

**Comment by OatmealDome** [comment]
You forgot the # sign on step 18, so now it just redirects to the main page of the wiki.
