### ISSUE TITLE
Comments on 9.2 update (III)

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#232]
The column for browser versions -2 through -6 does not mention cart upgrading to 9.3-10.7 even though the column for browser -0 does.  There are in fact rare situations where that would be necessary (user has a game with a 9.3-10.7 update, also has OOT+Powersaves or Cubic Ninja, but does not have a game with a 4.x or 6.x update).

No part of this guide mentions the possibility of using a cart to update to 9.2, and then using OOT/Ninjhax/Freakyhax for the rest of the guide.  Three E games have a 9.2 update and a version of Smash Brothers for U region has a 9.2 update. [This situation turned up in real life.](http://gbatemp.net/threads/installing-a9lh-on-a-3ds-thats-already-on-2-1.432723/)

**Comment by arromdee** [comment]
Also, [someone turned up with 2.2](http://gbatemp.net/threads/can-i-get-my-otp-on-2-2.432914/).  The Cubic Ninja OTP page only lists 1.0, 1.1, and 2.1.

**Comment by arromdee** [comment]
Edit: The guide for people with 1.x-2.x using Cubic Ninja OTP/Browser OTP says to get the OTP, then update to 9.2, then do part 5 launching the SafeA9LHInstaller from homebrew menu.  However, there is no step in there where they installed the homebrew menu.

**Comment by Plailect** [comment]
Fixed all of these.

**Comment by arromdee** [comment]
The guide still does not mention on the 9.2 update page the possibility of cart updating to 9.2 and then using a non-browser entry point for homebrew.

**Comment by Plailect** [comment]
Huh? It says to cart updates then do part 1...which includes non browser options.

**Comment by arromdee** [comment]
It says to do 9.3.0-0 through 10.7.0-0 cart update.  Nowhere does it even mention the possibility of doing a 9.2 cart update.  And a 9.2 update is both better and different because there isn't an extra step of having to downgrade to 9.2.

Also, the 4.x/6.x cart update link, and the 9.3-10.7 cart update link, both go to the same page.  But that page contains the text "You can now update to 9.2.0 with one of the methods in the appropriate section of the 9.2.0 Update chart here".  This text makes no sense if you are using the page as a 9.3-10.7 link.  It probably should say something like "If you are doing a cart update to 4.x/6.x, you can now update to 9.2.0 with one of the methods in the appropriate section of the 9.2.0 Update chart here.  If you are doing a cart update to 9.3-10.7, proceed to step 1 and then 2.  If you are doing a cart update to 9.2, proceed to step 1 and then 3."

**Comment by Plailect** [comment]
Part 2 includes info for existing 9.2 users to skip, but otherwise I've fixed these issues.
