### ISSUE TITLE
Some more slight Part 1 fixes

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#273]
The 4th paragraph of the overview in Part 1 says that "All versions above 9.9.0 include a browser version check that will not allow you to go to any sites if you are not on the latest system version, which means you'd normally have to update to the latest to run browserhax, but that would result in patching out browserhax."

This should be fixed to say that browserhax would not be patched by updating to 11.0, but it would require you to downgrade your firmware (using hardmod/dsiware) in order to complete part 2, so you still shouldn't do so.

Also, many users have reported that the browserhax auto page was not able to load on their 3DS without using an alternate DNS via internet settings such as Google DNS (primary: 8.8.8.8 secondary: 8.8.4.4) or Tubehax DNS (107.211.140.065). Apparently many DNS servers block access to the site, think it doesn't exist, and redirect forever or to a malware page, among other issues. However, the alternate DNSes I just listed actually load the page as intended every time. Adding steps to use those alternative DNSes in the guide for Part 1 browserhax would probably be a good idea. 

Also, in Step 8 of Part 1, the reference to sliderhax should be removed as the browserhax auto page will no longer redirect to it.

**Comment by maorninja** [comment]
1. A work around exists
2. Browserhax supports 11.0

On Jul 28, 2016, at 10:08 AM, jaxrogers2 <notifications@github.com<mailto:notifications@github.com>> wrote:


All versions above 9.9.0 include a browser version check that will not allow you to go to any sites if you are not on the latest system version, which means you'd normally have to update to the latest to run browserhax, but that would result in patching out browserhax.

-

**Comment by arromdee** [comment]
Additional part 1 fixes:
-- Because [the browser bypass doesn't work on 10.7 and 11.0](https://www.3dbrew.org/wiki/Internet_Browser#v10.7_2), you need to warn people on 10.7 and 11.0  to not ever use the browser when it is possible to reach Nintendo's servers, and to set a DNS that will prevent contacting Nintendo's servers.
-- Does browserhax work with 11.0 + hardmod/DSiware downgrade?  Or does it require the NATIVE_FIRM to match the browser?  If it doesn't work, you need a note; if it does work, it should say so.
--  "9.9.0 - 10.5.0: Follow this guide as written" and ">9.0.0 but with a browser version (the last number in the version, such as 11.0.0-33) of less than -20" now needs to take into account the fact that there are several ways of getting an unusable browser.  I suggest something like this:

"On 9.0.0-up your browser version may be unusable for downgrading under the following circumstances:
1) Browser version less than -20
2) Updated with a cart and you have a stub browser
3) Your firmware is 10.7 or higher (so you can't use the version bypass) and you have previously run your browser at a time when it could detect a newer firmware on Nintendo's servers.  Note: Currently this applies only to 10.7 since there is no firmware newer than 11.0.

...

9.0.0 - 9.8.0 with usable browser: Follow this guide, but skip changing the date and time and initializing savedata in the beginning.

9.9.0 - 11.0.0 with usable browser: Follow this guide as written.

>9.0.0 without usable browser:..."

-- "BASICSploit (requires SmileBASIC)/smilehax (requires SmileBASIC)" should say "BASICSploit (requires SmileBASIC 3.2.1 US)/smilehax (requires SmileBASIC 3.3.1 US/JP)"
-- "smashbroshax (requires Super Smash Bros." should say "smashbroshax (requires Super Smash Bros. [that does not have 1.1.0 preinstalled on the cartridge](https://www.reddit.com/r/3dshacks/comments/4tr2tn/how_to_check_version_of_smashbros_for_smashhax/)"

**Comment by jaxrogers2** [comment]
arromdee:
Currently, the browser version check only requires that users are on 10.7.0-32 (browser version -32) or above to use the web browser, so while the browser version check bypass no longer works since 10.7, 10.7 and 11.0 have the same browser version (it was not updated) so browserhax currently works on 10.7 and 11.0

**Comment by arromdee** [comment]
That's very different.  Never mind...

(as far as browser is concerned anyway).

**Comment by Ev1lbl0w** [comment]
The thing is, during the 9.2 downgrade, a soft-brick can happen. It's been happenning lately. But, if you set up a DNS like Tubehax before, you can't uptade your Nintendo 3DS and, as such, it becomes almost a hardbrick.

**Comment by Plailect** [comment]
Fixed

**Comment by arromdee** [comment]
This isn't completely fixed.  The browser version check was added in 10.7.  So
-- "9.9.0 - 10.5.0: Follow this guide as written." should say 10.6.0 instead.
-- >=9.9.0 but with a browser version (the last number in the version, such as 11.0.0-33) of greater than -32:: should just say ">= 10.7".

**Comment by Plailect** [comment]
It was fixed in 10.7 so the workaround didn't work, not added.

Otherwise that's correct.
