### ISSUE TITLE
9.2.0 downgrade N3DS

### ISSUE THREAD

**Issue by Deoxarn** [Plailect/Guide#391]
So iam at the part where im trying to downgrade to 9.2.0 everything have gone fine until this part.

When pressing (Y) for downgrade the following happens.

Checking for am:u...
Did not get am:u handle!

Attemting svchax...
Initted svchax...

Innited services...
Checking for am:u...

Got am:u handle!

Beginning downgrade...
Getting firmware files information...
Getting firmware files version...
NATIVE_FIRM (0004013820000002.cia) is v17120
Verifying firmware files...

titleException:
main.cpp:200: Result: 0x0
Too many titles in /updates/ found!

Have tried different sources for the 9.2.0 update but still get stuck on this. Im on E version if that matters.

What could be wrong?

**Comment by iuzwpr2p39rh7w** [comment]
You should not need to try different sources for the update.
There should be 104 .cia files in your `updates` folder, you seem to have too many. Just delete the whole folder, get the update from [here](https://github.com/Plailect/Guide/wiki/9.2.0-Downgrade#what-you-need) and verify its file integrity.
To do so either use your torrent client's verification option or a checksum generation tool.
Your `9.2.0-20E(Full)_n3DS.zip` file should have the following checksums:
MD5: `aaa5960a3061da1f08d944d8e7017bd6`
SHA-1: `306d0aa8cd195f9ee4388a9686db5658a330b59b`
SHA-256: `e7fbaf4ee01b81a3c2297028ef3fddc002f6933bfd20c2453bc6137bda89e5fd`
Afterwards copy the `updates` folder from `9.2.0-20E(Full)_n3DS.zip` to the root of your SD card and retry the downgrade process.

**Comment by Deoxarn** [comment]
checksums are a match to what you wrote and there are 104 files in the updates folder on the root of the SD card.

**Comment by heyiterry** [comment]
A similar problem occurred at my n3ds as well. My n3ds is 10.7.0-32J now and I want to downgrade to 9.2.0-20J. I downloaded the 9.2.0-20J(Full)_n3DS.zip file here and there is total 102 .cia inside. But sysDowngrader still reported too fewer titles. How many .cia files should be there in 9.2.0-20J(Full)_n3DS.zip? Thanks a lot!

**Comment by iuzwpr2p39rh7w** [comment]
Plailect/sysDowngrader/issues/3

**Comment by heyiterry** [comment]
Are the filelists of J and E the same?

**Comment by kloklojul** [comment]
no if i recall correctly the J cias should be fewer. In past tutorials one had to delete some cias if they had a J console. Don't qoute me on that though.

**Comment by heyiterry** [comment]
Oh it works! Great! I tried v2 earlier and failed. This time I used the latest v5 and finally succeeded!

**Comment by heyiterry** [comment]
Another question, my n3ds automatically reboot after downgrade without taking away the tf card. I can see the version No. 9.1.0-20J in settings and I can launch Decrypt9WIP in HBL. Is this a perfect downgrade?

**Comment by Plailect** [comment]
Fixed with https://github.com/Plailect/sysDowngrader/commit/44b462f527cf8fdc79c71ad6e4f427c01f7a561e, release coming soon

**Comment by harryhobbes** [comment]
@Plailect any idea when the new release with this fix will drop? I'm using 1.0.3 and still getting this issue. Any recommendations on what I can do in the meantime to fix this?
