### ISSUE TITLE
A minor note about emu/redNAND creation with the new guide

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#394]
The new ctrtransfer guide is amazing! But as I was looking over it, there is only one slight problem. If somebody started at a lower firmware (such as 4.X, 6.X, etc.) and then did the ctrtransfer through Decrypt9 to downgrade to 2.1 and get A9LH, that means that they will never be able to create an emu/redNAND in the future because the backup that they have (created before the transfer) is for that lower firmware, which (if it is low enough) will not boot on an emu/redNAND. And since flashing sysNAND to emu/redNAND with A9LH installed also makes the emu/redNAND unbootable, that means that those users are simply out of luck. In order to fix this, the guide should direct people at these low firmwares that cannot be booted in CFW red/emuNAND to update to a firmware that will boot in an emu/redNAND and then perform the ctrtransfer. However, since an emu/redNAND is entirely optional when A9LH is installed, this process should be optional also.

**Comment by Plailect** [comment]
This is because of an issue in the way d9 stores the NCSD header backups in ctrtransfer systems and how Luma3DS boots traditional EmuNAND. This issue does *not* affect RedNANDs, and should be fixed soon.

For now, creating a RedNAND from SysNAND using EmuNAND9 then booting it with Luma will work.

**Comment by arromdee** [comment]
It sounds like this issue still would legitimately arise for 2.1.0-4 since the procedure for that doesn't involve a cart update and Luma can't boot 2.1 with or without a d9 fix.

**Comment by dark-samus** [comment]
At this point, we do a ctrtransfer to 9.2, then make an emuNAND from the
resulting image
